apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-ha
servers: 3
agents: 2
image: rancher/k3s:v1.30.2-k3s2
network: k3d-ha-network

options:
  k3d:
    wait: true
    timeout: "300s"
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - "server:*"
      - arg: "--disable=servicelb"
        nodeFilters:
          - "server:*"
      - arg: "--disable-network-policy"
        nodeFilters:
          - "server:*"
      - arg: "--flannel-backend=none"
        nodeFilters:
          - "server:*"
      - arg: "--disable-kube-proxy"
        nodeFilters:
          - "server:*"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

ports:
  - port: "8180:80"
    nodeFilters:
      - "loadbalancer"
  - port: "8543:443"
    nodeFilters:
      - "loadbalancer"
