---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
  labels:
    app.kubernetes.io/name: otel-demo
    app.kubernetes.io/part-of: k3d-lab
    # Enable Istio sidecar injection if using Istio
    # istio-injection: enabled
